// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj7SVtmWs9jLYQUI-sJZwxPutE06UJ3lQ',
    appId: '1:245897215956:web:bb8012ba3a0f22e319e041',
    messagingSenderId: '245897215956',
    projectId: 'weather-e8830',
    authDomain: 'weather-e8830.firebaseapp.com',
    storageBucket: 'weather-e8830.firebasestorage.app',
    measurementId: 'G-6353C5VNMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBUg5p50-zkrQB4keN-akt3eaz7woE74Q',
    appId: '1:245897215956:android:0079165fead47a0919e041',
    messagingSenderId: '245897215956',
    projectId: 'weather-e8830',
    storageBucket: 'weather-e8830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCiZ5q7m0dY1Oaco2fsWKF9GPRprMenk',
    appId: '1:245897215956:ios:e74ebf465c5b174a19e041',
    messagingSenderId: '245897215956',
    projectId: 'weather-e8830',
    storageBucket: 'weather-e8830.firebasestorage.app',
    iosBundleId: 'com.shokhrukhbek.weatherService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJCiZ5q7m0dY1Oaco2fsWKF9GPRprMenk',
    appId: '1:245897215956:ios:e74ebf465c5b174a19e041',
    messagingSenderId: '245897215956',
    projectId: 'weather-e8830',
    storageBucket: 'weather-e8830.firebasestorage.app',
    iosBundleId: 'com.shokhrukhbek.weatherService',
  );
}
